# Generated by Django 5.0.1 on 2024-01-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_weather', models.BooleanField(default=False)),
                ('bbc_news', models.BooleanField(default=False)),
                ('google_search', models.BooleanField(default=False)),
                ('google_calendar_check', models.BooleanField(default=False)),
                ('google_calendar_add', models.BooleanField(default=False)),
                ('google_maps_directions', models.BooleanField(default=False)),
                ('google_maps_info', models.BooleanField(default=False)),
                ('set_reminder', models.BooleanField(default=False)),
                ('list_reminder', models.BooleanField(default=False)),
                ('edit_reminder', models.BooleanField(default=False)),
                ('smart_home_control', models.BooleanField(default=False)),
                ('discord_message', models.BooleanField(default=False)),
                ('save_notes', models.BooleanField(default=False)),
                ('list_notes', models.BooleanField(default=False)),
                ('edit_notes', models.BooleanField(default=False)),
            ],
        ),
    ]
