# Generated by Django 5.0.1 on 2024-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picovoice_access_key', models.CharField(max_length=255)),
                ('openai_api_key', models.CharField(max_length=255)),
                ('openai_api_base', models.CharField(max_length=255)),
                ('discord_token', models.CharField(blank=True, max_length=255, null=True)),
                ('google_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('google_cse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('home_assistant_token', models.CharField(blank=True, max_length=255, null=True)),
                ('home_assistant_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
