# Generated by Django 5.0.1 on 2024-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_configurationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcustomization',
            name='system_prompt',
        ),
        migrations.AlterField(
            model_name='generalcustomization',
            name='assistant_name',
            field=models.CharField(default='Jarvis', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalcustomization',
            name='llm_model',
            field=models.CharField(default='gpt-3.5-turbo-1106', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalcustomization',
            name='voice_diarization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalcustomization',
            name='wake_word',
            field=models.CharField(default='Jarvis', max_length=50),
        ),
    ]
