# Generated by Django 5.0.1 on 2024-01-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_remove_generalcustomization_system_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_flow', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generalcustomization',
            name='wake_word',
            field=models.CharField(default='jarvis', max_length=50),
        ),
    ]
