# Generated by Django 5.0.1 on 2024-01-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0006_alter_setupflow_setup_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsetting',
            name='home_assistant_url',
            field=models.CharField(blank=True, default='http://localhost:8123', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='openai_api_base',
            field=models.CharField(default='https://api.openai.com/v1', max_length=255),
        ),
    ]
